version: '3'
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: entaingo
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - db
    networks:
      - entaingo_network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user@56
      POSTGRES_PASSWORD: password@Entaingo
      POSTGRES_DB: entaingo
    ports:
      - "5433:5432"
    networks:
      - entaingo_network

networks:
  entaingo_network:
    driver: bridge
